#index:
#    path: /
#    controller: App\Controller\DefaultController::index
controllers:
  resource: '../src/Controller/'
  type: annotation
captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"